// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: licenses.sql

package queries

import (
	"context"
)

const getLicenseByID = `-- name: GetLicenseByID :one
SELECT id, name FROM licenses WHERE id = $1
`

func (q *Queries) GetLicenseByID(ctx context.Context, id int32) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByID, id)
	var i License
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
